server:
  port: 8082

spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: NZHOSHWRKWQZTXMG
    username: z17631089214@163.com
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: 39.102.65.157
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    timeout: 10000ms
    host: 39.102.65.157
    port: 6379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5
